set $bg 272822
set $fg f8f8f2
set $muted 75715e
set $accent 66d9ef
set $accent_alt ae81ff
set $urgent f92672

client.focused $accent $accent $bg $accent_alt $accent
client.focused_inactive $muted $muted $fg $muted $muted
client.unfocused $bg $bg $muted $bg $bg
client.urgent $urgent $urgent $fg $urgent $urgent
client.placeholder $bg $bg $fg $bg $bg
