output HDMI-A-1 mode 1920x1080@60Hz position 0 0 scale 1
output HDMI-A-1 adaptive_sync off
output HDMI-A-1 scale_filter nearest
output DP-1 mode 1920x1080@60Hz position 1920 0 scale 1
output DP-1 adaptive_sync off
output DP-1 scale_filter nearest
output * bg $wallpaper fill

workspace 1 output HDMI-A-1
workspace 2 output DP-1
