for_window [window_role="dialog"] floating enable
for_window [window_role="pop-up"] floating enable
for_window [title="Picture-in-Picture"] floating enable

for_window [app_id="pavucontrol"] floating enable, resize set 900 600, move position center
for_window [app_id="blueman-manager"] floating enable, move position center
for_window [app_id="nm-connection-editor"] floating enable, move position center
