output * bg $wallpaper fill

exec_always --no-startup-id /bin/sh -c 'if [ "$HOSTNAME" = "starbase" ]; then swaymsg \
  output HDMI-A-1 mode 1920x1080@60Hz position 0 0 scale 1 \
  output HDMI-A-1 adaptive_sync off \
  output HDMI-A-1 scale_filter nearest \
  output DP-3 mode 1920x1080@60Hz position 1920 0 scale 1 \
  output DP-3 adaptive_sync off \
  output DP-3 scale_filter nearest \
  workspace 1 output HDMI-A-1 \
  workspace 2 output DP-3; \
fi'
