[manager]
show_hidden = true
sort_by = "alphabetical"
sort_dir_first = true

[preview]
image_filter = "lanczos3"
image_quality = 80

[opener]
open = [
  { run = 'xdg-open "$@"', desc = "Open", for = "unix" }
]

[open]
rules = [
  { mime = "*", use = "open" }
]
